version: '3'
services:
  myphp:
    build: .
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html/
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
  phppgadmin:
    image: dockage/phppgadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db